MySignal/MySignal/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('index.urls', 'index'), namespace='index'))
]

MySignal/index/urls.py
from django.urls import path
from index.views import order_info, create_order, cancel_order

urlpatterns = [
    # 定义路由
    path('create/', create_order, name='create'),
    path('cancel/', cancel_order, name='cancel'),
]

MySignal/templates/order.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>订单</title>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
            crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"
            integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"
            integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13"
            crossorigin="anonymous"></script>
</head>


<body>
<div class="container">
    <form method="post">
        <div class="mb-3">
            <label for="exampleInputProductID" class="form-label">商品ID：</label>
            <input type="text" class="form-control" id="exampleInput" name="ProductID">
        </div>
        <div class="mb-3 {{ display }}">
            <label for="exampleInputProductQuantity" class="form-label">商品数量：</label>
            <input type="text" class="form-control" id="exampleInputProductQuantity" name="ProductQuantity">
        </div>
        <div class="mb-3 form-check">
            <label class="form-check-label" for="exampleCheck1">确认订单信息</label>
            <input type="checkbox" class="form-check-input" id="exampleCheck" name="Check">
        </div>
        <button type="submit" class="btn btn-success {{ display }}" id="create" name="create"
                formaction="{% url 'index:create' %}" value="create">创建订单
        </button>
        <button type="submit" class="btn btn-danger" id="cancel" name="cancel" formaction="{% url 'index:cancel' %}"
                value="cancel">取消订单
        </button>
    </form>
</div>
</body>
</html>